let data =  [
    {
        id: 1,
        coverImage: "shirt-1.png",
        title: "Amazon Brand - Symbol",
        type: "shirt",
        description: "Men's Slim Fit Shirt",
        price: 500,
        // offer: "Buy 2 get 5% off, Buy 3 get 10% off",
        delivery: "FREE Delivery by Amazon",
        // stocks: "Only 2 left in stock.",
    },

    {
        id: 2,
        coverImage: "pant-2.png",
        title: "Amazon Brand - Symbol",
        type: "shirt",
        description: "Men's Slim Fit Shirt",
        price: 500,
        // offer: "Buy 2 get 5% off, Buy 3 get 10% off",
        delivery: "FREE Delivery by Amazon",
        // stocks: "Only 2 left in stock.",
    },

    {
        id: 3,
        coverImage: "shirt-3.png",
        title: "Amazon Brand - Symbol",
        type: "shirt",
        description: "Girls Stylish Jeans",
        price: 350,
        // offer: "Buy 3 get 10% off    ",
        delivery: "FREE Delivery by Amazon",
        // stocks: "Only 2 left in stock.",
    },

    {
        id: 4,
        coverImage: "shirt-6.png",
        title: "Amazon Brand - Symbol",
        type: "shirt",
        description: "Men's Slim Fit Shirt",
        price: 500,
        // offer: "Buy 2 get 5% off, Buy 3 get 10% off",
        delivery: "FREE Delivery by Amazon",
        // stocks: "Only 2 left in stock.",
    },
    {
        id: 5,
        coverImage: "shirt-7.png",
        title: "Amazon Brand - Symbol",
        type: "shirt",
        description: "Men's Slim Fit Shirt",
        price: 500,
        // offer: "Buy 2 get 5% off, Buy 3 get 10% off",
        delivery: "FREE Delivery by Amazon",
        // stocks: "Only 2 left in stock.",
    },

    {
        id: 6,
        coverImage: "pant-1.png",
        title: "Amazon Brand - Symbol",
        type: "pant",
        description: "Girls Stylish Jeans",
        price: 350,
        // offer: "Buy 3 get 10% off",
        delivery: "FREE Delivery by Amazon",
        // stocks: "Only 2 left in stock.",
    },

    {
        id: 7,
        coverImage: "pant-2.png",
        title: "Amazon Brand - Symbol",
        type: "pant",
        description: "Men's Slim Fit Shirt",
        price: 500,
        // offer: "Buy 2 get 5% off, Buy 3 get 10% off",
        delivery: "FREE Delivery by Amazon",
        // stocks: "Only 2 left in stock.",
    },
    {
        id: 8,
        coverImage: "shirt-1.png",
        title: "Amazon Brand - Symbol",
        type: "pant",
        description: "Men's Slim Fit Shirt",
        price: 500,
        // offer: "Buy 2 get 5% off, Buy 3 get 10% off",
        delivery: "FREE Delivery by Amazon",
        // stocks: "Only 2 left in stock.",
    },

    {
        id: 9,
        coverImage: "pant-2.png",
        title: "Amazon Brand - Symbol",
        type: "pant",
        description: "Men's Slim Fit Shirt",
        price: 500,
        // offer: "Buy 2 get 5% off, Buy 3 get 10% off",
        delivery: "FREE Delivery by Amazon",
        // stocks: "Only 2 left in stock.",
    },

    {
        id: 10,
        coverImage: "pant-1.png",
        title: "Amazon Brand - Symbol",
        type: "pant",
        description: "Girls Stylish Jeans",
        price: 350,
        // offer: "Buy 3 get 10% off",
        delivery: "FREE Delivery by Amazon",
        // stocks: "Only 2 left in stock.",
    },

    {
        id: 11,
        coverImage: "shirt-3.png",
        title: "Amazon Brand - Symbol",
        type: "pant",
        description: "Men's Slim Fit Shirt",
        price: 500,
        // offer: "Buy 2 get 5% off, Buy 3 get 10% off",
        delivery: "FREE Delivery by Amazon",
        // stocks: "Only 2 left in stock.",
    },
    {
        id: 12,
        coverImage: "pant-2.png",
        title: "Amazon Brand - Symbol",
        type: "pant",
        description: "Men's Slim Fit Shirt",
        price: 500,
        // offer: "Buy 2 get 5% off, Buy 3 get 10% off",
        delivery: "FREE Delivery by Amazon",
        // stocks: "Only 2 left in stock.",
    },

    {
        id: 13,
        coverImage: "pant-1.png",
        title: "Amazon Brand - Symbol",
        type: "pant",
        description: "Girls Stylish Jeans",
        price: 350,
        // offer: "Buy 3 get 10% off",
        delivery: "FREE Delivery by Amazon",
        // stocks: "Only 2 left in stock.",
    },

    {
        id: 14,
        coverImage: "shirt-3.png",
        title: "Amazon Brand - Symbol",
        type: "pant",
        description: "Men's Slim Fit Shirt",
        price: 500,
        // offer: "Buy 2 get 5% off, Buy 3 get 10% off",
        delivery: "FREE Delivery by Amazon",
        // stocks: "Only 2 left in stock.",
    },
]

export default data;